import { Metadata } from "next";
import NavBar from "../components/NavBar";
import Header from "./components/Header";
import RestaurantCart from "./components/RestaurantCart";
import SideBar from "./components/SideBar";
import { PRICE, PrismaClient } from "@prisma/client";

export const metadata: Metadata = {
  title: "Search",
  description: "Generated by create next app",
  keywords: ["deepak", "page"],
};

const prisma = new PrismaClient();

interface searchParams {
  city?: string;
  region?: string;
  price?: PRICE;
}

const fetchRestaurants = (searchParams: searchParams) => {
  const where: any = {};

  if (searchParams.city) {
    const location = {
      name: {
        equals: searchParams.city.toLocaleLowerCase(),
      },
    };

    where.location = location;
  }
  if (searchParams.region) {
    const region = {
      name: {
        equals: searchParams.region.toLocaleLowerCase(),
      },
    };

    where.region = region;
  }

  if (searchParams.price) {
    const price = {
      equals: searchParams.price,
    };
    where.price = price;
  }

  const select = {
    id: true,
    name: true,
    main_image: true,
    price: true,
    location: true,
    slug: true,
    region: true,
  };

  return prisma.restaurant.findMany({
    where,
    select,
  });
};

const fetchLoactions = () => {
  return prisma.location.findMany();
};

const fetchRegions = () => {
  return prisma.region.findMany();
};

export default async function SearchPage({
  searchParams,
}: {
  searchParams: searchParams;
}) {
  const restaurants = await fetchRestaurants(searchParams);

  const locations = await fetchLoactions();

  const regions = await fetchRegions();

  console.log(restaurants);
  return (
    <>
      <Header />
      <div className="flex py-4 m-auto w-2/3 justify-between items-start">
        <SideBar
          locations={locations}
          regions={regions}
          searhPrams={searchParams}
        />
        <div className="w-5/6">
          {restaurants.length ? (
            restaurants.map((restaurant) => (
              <RestaurantCart restaurant={restaurant} />
            ))
          ) : (
            <p>sorry no retaurant was found</p>
          )}
        </div>
      </div>
    </>
  );
}
